# 檢查概念差異
print("=== 概念澄清 ===")
print("預設參數：")
print("- 初始投入 C0: $10,000")
print("- 年度投入: $12,000")
print("- 每月基準投入 C_period: $1,000 (12000/12)")
print("")
print("VA_Target 的含義：")
print("- VA_Target 是「累積目標價值」，不是「每月投入金額」")
print("- 第1期VA_Target = $11,102.37 表示第1期末的目標總資產價值")
print("- 這包括了 C0 的成長 + C_period 的影響")
print("")
print("如果您期望看到的是每月投入金額 C_period = $1,000")
print("那麼問題可能是概念混淆，而不是計算錯誤")
